name: 'kyle & christi'
favicon: null
layout_spectrum: 0.32017095759510994
typography_spectrum: 0.03586835227906704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.04652532213367522
  lightness: 0.6560145136900246
  saturation: 0.22011791914701462
  rhythmicContrast: 0.7290376827586442
purpose: []
